//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomEstateAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deals
    {
        public int ID { get; set; }
        public Nullable<int> Apartament { get; set; }
        public Nullable<int> IDOwner { get; set; }
        public Nullable<int> IDRealtor { get; set; }
        public Nullable<int> IDClient { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> DealPrice { get; set; }
    
        public virtual Apartaments Apartaments { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Owners Owners { get; set; }
        public virtual Realtors Realtors { get; set; }
    }
}
