//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomEstateAgency
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstateAgencyEntities : DbContext
    {
        public EstateAgencyEntities()
            : base("name=EstateAgencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartaments> Apartaments { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Deals> Deals { get; set; }
        public virtual DbSet<Flats> Flats { get; set; }
        public virtual DbSet<GarageParking> GarageParking { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Houses_Plots> Houses_Plots { get; set; }
        public virtual DbSet<Owners> Owners { get; set; }
        public virtual DbSet<Realtors> Realtors { get; set; }
    }
}
